# Generated by Django 4.0.5 on 2023-04-19 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tipoproducto',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(error_messages={'unique': 'Este SKU ya está registrado'}, max_length=10, unique=True)),
                ('nombre_producto', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=1000)),
                ('Precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('precio_oferta', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen_producto', models.ImageField(blank=True, upload_to='productos')),
                ('activo', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appi.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appi.proveedor')),
            ],
        ),
    ]
