# Generated by Django 4.2 on 2023-05-02 02:09

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('nombre_dueño', models.CharField(max_length=50, null=True)),
                ('estado', models.IntegerField(choices=[[0, 'Reservado'], [1, 'En espera de revisión'], [2, 'En revision'], [3, 'en espera de repuestos'], [4, 'En espera de Atencion del técnico'], [5, 'En Atención de técnico'], [6, 'Completado'], [7, 'Cancelado']], default=0)),
                ('fecha_creacion', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproveedor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('RUT', models.CharField(blank=True, default='', error_messages={'unique': 'El rut ya está registrado.'}, max_length=13, unique=True)),
                ('nombre_real', models.CharField(default='', max_length=50)),
                ('nacimiento', models.DateField(null=True)),
                ('genero', models.IntegerField(choices=[[0, 'Hombre'], [1, 'Mujer'], [2, 'No especificado']], default=2)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('Direccion', models.CharField(default='', max_length=300)),
                ('comuna', models.IntegerField(blank=True, choices=[[0, 'Peñaflor'], [1, 'Cerrillos'], [2, 'Cerro Navia'], [3, 'Conchalí'], [4, 'El Bosque'], [5, 'Estación Central'], [6, 'Huechuraba'], [7, 'Independencia'], [8, 'La Cisterna'], [9, 'La Florida'], [10, 'La Granja'], [11, 'La Pintana'], [12, 'La Reina'], [13, 'Las Condes'], [14, 'Lo Barnechea'], [15, 'Lo Espejo'], [16, 'Lo Prado'], [17, 'Macul'], [18, 'Maipú'], [19, 'Ñuñoa'], [20, 'Pedro Aguirre Cerda'], [21, 'Peñalolén'], [22, 'Providencia'], [23, 'Pudahuel'], [24, 'Quilicura'], [25, 'Quinta Normal'], [26, 'Recoleta'], [27, 'Renca'], [28, 'San Joaquín'], [29, 'San Miguel'], [30, 'San Ramón'], [31, 'Vitacura'], [32, 'Puente Alto'], [33, 'Pirque'], [34, 'San José de Maipo'], [35, 'Colina'], [36, 'Lampa'], [37, 'Tiltil'], [38, 'San Bernardo'], [39, 'Buin'], [40, 'Calera de Tango'], [41, 'Paine'], [42, 'Melipilla'], [43, 'Alhué'], [44, 'Curacaví'], [45, 'María Pinto'], [46, 'San Pedro'], [47, 'Talagante'], [48, 'El Monte'], [49, 'Isla de Maipo'], [50, 'Padre Hurtado']], null=True)),
                ('foto_de_Usuario', models.ImageField(null=True, upload_to='usuarios')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['nombre_real'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(error_messages={'unique': 'Este SKU ya está registrado'}, max_length=10, unique=True)),
                ('nombre_producto', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=1000)),
                ('Precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('precio_oferta', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen_producto', models.ImageField(blank=True, upload_to='productos')),
                ('activo', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appi.categoria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appi.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Ordenxproducto',
            fields=[
                ('id_ordenxproducto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_orden_relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appi.orden')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appi.producto')),
            ],
            options={
                'ordering': ['-id_ordenxproducto'],
            },
        ),
    ]
